server:
  port: 5000

spring:
  application:
    name: todo-app
    
  datasource:
    url: jdbc:mysql://database-1.cghscqwgostc.us-east-1.rds.amazonaws.com:3306/hr
    username: admins
    password: yash1234
    
#  h2:
#    console:
#      path: /h2
#      enabled: true
#      settings:
#        web-allow-others: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
        
        
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
      
    
    